DROP DATABASE IF EXISTS LP2A4_EXE;

CREATE DATABASE IF NOT EXISTS LP2A4_EXE;

USE LP2A4_EXE;

CREATE TABLE IF NOT EXISTS Contatos (
	idcon INTEGER AUTO_INCREMENT,
	nome VARCHAR(255),
	fone VARCHAR(15),
	email VARCHAR (1000),
	PRIMARY KEY (idcon)
);
